### ISSUE TITLE
setColorTemperature does not seem to work

### ISSUE THREAD

**Issue by SteffenKn** [sinricpro/nodejs-sdk#8]
I'm currently switching from sinric to sinricpro and apparently setColorTemperature doesn't work in sinricpro.

Here is my code if that helps:
https://github.com/SteffenKn/WS2801-alexa/blob/develop/src/alexa-device-handler.ts

**Comment by kakopappa** [comment]
Link doesn't work. Private repo?

**Comment by SteffenKn** [comment]
I changed the link after creating the issue, maybe you clicked the old one.

**Comment by SteffenKn** [comment]
Correct me if I'm wrong, but shouldn't there be an if statement for setColorTemperature in this code:
https://github.com/sinricpro/nodejs-sdk/blob/ea87b3763a738cde5cf56bee7e814f3019692247/lib/cbhandler.js#L61-L189

**Comment by kakopappa** [comment]
Yes it looks like setColorTemperature is missing here

**Comment by kakopappa** [comment]
@SteffenKn  I have updated the SDK to support setColorTemperature. Dhanush will push this to npm repo soon.

Example
https://github.com/sinricpro/nodejs-sdk/blob/master/examples/light-bulb/light-bulb.js

**Comment by SteffenKn** [comment]
Sounds good. Thanks for the quick fix.

**Comment by SteffenKn** [comment]
I just tested the changes and the callback is now triggered, but Alexa always claims that the device is not responding.

This is due to an bug in the ColorTemperature Controller: 
https://github.com/sinricpro/nodejs-sdk/blob/232d5e71a8b25909c78107d5ef8989d6625db82d/lib/contorllers/color_temperature.js#L16

This line should end with ```resolve(payload.value);```  instead of ```resolve(payload.colorTemperature);```

**Comment by kakopappa** [comment]
Thanks 

Fixed. Wil update the npm soon https://github.com/sinricpro/nodejs-sdk/commit/89b7fc237d81ff71ae2a1e98f5ad7d899eeeb40a

**Comment by SteffenKn** [comment]
Just a friendly reminder in case you forgot: The package is not yet published.
